"""add user layout_json column

Revision ID: f55633c21386
Revises: e40a1325f5c8
Create Date: 2026-03-02 13:39:47.997468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55633c21386'
down_revision: Union[str, None] = 'e40a1325f5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('layout_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'layout_json')
    # ### end Alembic commands ###
